### ISSUE TITLE
Please provide a "product" description

### ISSUE THREAD

**Issue by ErstwhileWork** [material-components/material-components-android-compose-theme-adapter#33]
We (all of us) seem to have fallen into the habit of assuming the folks have time to read and study code to figure out what is going in, we need to change that.

If one doesn't have a high-level description of what we are trying to do, how can we actually quickly and successfully "do" it.

Please provide that high level description that is missing.

**Comment by chrisbanes** [comment]
The description is quite clear what the library does in my opinion. If you can think of a better way to describe a migration tool, feel free to send a PR.
