### ISSUE TITLE
Compose-beta09-crash

### ISSUE THREAD

**Issue by polivmi1** [material-components/material-components-android-compose-theme-adapter#70]
There seems to be in issue with the current version beta08 and new version of compose beta09

Fatal Exception: java.lang.NoSuchFieldError
No field Normal of type Landroidx/compose/ui/text/font/FontStyle; in class Landroidx/compose/ui/text/font/FontStyle; or its superclasses (declaration of 'androidx.compose.ui.text.font.FontStyle' appears in ...)

**Comment by bmc08gt** [comment]
Most likely this will need to be updated to beta09 like other compose libaries.

**Comment by ricknout** [comment]
Yes, we're in the process of updating this to Compose 1.0.0-beta09. Sorry for the delay!

**Comment by ricknout** [comment]
It's been released: https://github.com/material-components/material-components-android-compose-theme-adapter/releases/tag/v1.0.0-beta09
