### ISSUE TITLE
Can not use serif-monospace

### ISSUE THREAD

**Issue by wiryadev** [material-components/material-components-android-compose-theme-adapter#80]
MDC Adapter can not display serif-monospace, but works with other fontFamily like monospace and sans-serif-black.
<table style="width:100%">
  <tr>
    <th>Monospace</th>
    <th>Sans Serif Black</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/26060382/128606249-b807f065-85b2-4d22-9b26-738fa0317f2e.png"></td>
    <td><img src="https://user-images.githubusercontent.com/26060382/128606169-bfae7475-4aa6-4b86-97da-7680877576b6.png"></td>
  </tr>
</table>

And here is Serif Monospace in Compose and Views XML:
<table style="width:100%">
  <tr>
    <th>Compose with MDC</th>
    <th>Views XML (how it should looks like)</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/26060382/128606306-f8be08de-a975-4ad6-85ff-6c3b8f6e2e8e.png"></td>
    <td><img src="https://user-images.githubusercontent.com/26060382/128606328-a45fae1c-d626-4a40-958f-755b8c824791.png"></td>
  </tr>
</table>

</br>
The fact that it doesnt exist in google fonts make it harder to use this font manually in Compose:

![image](https://user-images.githubusercontent.com/26060382/128606452-b586aded-7aba-46ad-b06e-c30d30f300dd.png)

**Additional Info**
Sample app to reproduce that is available [**here**](https://github.com/wiryadev/SerifMonoRepro).

**Comment by ricknout** [comment]
Compose currently only supports a subset of the `fontFamily` constants, and `serif-monospace` is unfortunately not one of them:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-text/src/commonMain/kotlin/androidx/compose/ui/text/font/FontFamily.kt;l=31

Also see the TODO in this library:
https://github.com/material-components/material-components-android-compose-theme-adapter/blob/develop/lib/src/main/java/com/google/android/material/composethemeadapter/TypedArrayUtils.kt#L216

**Comment by wiryadev** [comment]
Understood, thanks for explanation
