### ISSUE TITLE
Stable release dependency on MCD alpha

### ISSUE THREAD

**Issue by niqo01** [material-components/material-components-android-compose-theme-adapter#97]
I was wondering if there are specific reasons why stable versions of this library depends on alpha version of material design? Right now the version 1.1.15 depends on MDC 1.7.0-alpha03. 
Would it be and issue if I use version 1.1.15 and force downgrading to the MDC 1.6.1? Or does this library uses features from MCD alpha?

**Comment by ricknout** [comment]
Good point, thanks.

The Compose Material 3 artifact does use features from the alpha, whereas the Compose Material artifact doesn't. 

Addressed here: 9f251bf5f81d93fcd4997f0720d823f0b21eef12
