### ISSUE TITLE
Not possible to update to 1.0.22 / 1.1.22

### ISSUE THREAD

**Issue by mkochenough** [material-components/material-components-android-compose-theme-adapter#99]
In two projects, one using 'com.google.android.material:compose-theme-adapter-3:1.0.22', the other using 'com.google.android.material:compose-theme-adapter:1.1.22' I get similar error message:

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsGenericDebug'.
> Could not resolve all files for configuration ':app:genericDebugRuntimeClasspath'.
   > Could not find material-components-android-compose-theme-adapter:core:unspecified.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/material-components-android-compose-theme-adapter/core/unspecified/core-unspecified.pom
       - https://repo.maven.apache.org/maven2/material-components-android-compose-theme-adapter/core/unspecified/core-unspecified.pom
     Required by:
         project :app > com.google.android.material:compose-theme-adapter-3:1.0.22

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

It seems the new core dependency is not publicly available.

**Comment by ricknout** [comment]
There was a delay between the GitHub release and the artifacts becoming available on gMaven. They should be available now:
* https://maven.google.com/web/index.html#com.google.android.material:compose-theme-adapter:1.1.22
* https://maven.google.com/web/index.html#com.google.android.material:compose-theme-adapter-3:1.0.22

**Comment by mkochenough** [comment]
Error still happens.

**Comment by ricknout** [comment]
This should now be fixed in the latest releases:
* Material: https://github.com/material-components/material-components-android-compose-theme-adapter/releases/tag/material-v1.2.0
* Material 3: https://github.com/material-components/material-components-android-compose-theme-adapter/releases/tag/material3-v1.1.0
* Core: https://github.com/material-components/material-components-android-compose-theme-adapter/releases/tag/core-v1.0.0
